// sensor_msgs demo showing ARRAY/SEQUENCE support: publishes a
// sensor_msgs/msg/LaserScan whose `ranges` and `intensities` are float32[]
// sequences (generated by rosidl_generator_dart).
//
// Verify from ROS 2:
//   ros2 topic echo /scan sensor_msgs/msg/LaserScan
import 'dart:ffi';
import 'dart:io';
import 'dart:math';
import 'package:rcldart/rcldart.dart' as rcldart;
import 'package:rcldart/src/node.dart';
import 'package:std_msgs/std_msgs.dart';
import 'package:rcldart_example/sensor_msgs_gen/laser_scan.dart';

void main() {
  rcldart.RclDart().init();
  final node = rcldart.RclDart().createNode('laser', 'examples');

  final pub = node.createPublisher<SensorMsgsLaserScan>(
    topic_name: '/scan',
    messageType: SensorMsgsLaserScan(),
  );
  print('publishing sensor_msgs/msg/LaserScan on /scan');

  const n = 16;
  final rng = Random();
  for (var i = 0; i < 40; i++) {
    final msg = SensorMsgsLaserScan()
      ..angleMin = -pi / 2
      ..angleMax = pi / 2
      ..angleIncrement = pi / n
      ..rangeMin = 0.1
      ..rangeMax = 10.0
      ..ranges = List.generate(n, (j) => 1.0 + rng.nextDouble() * 5.0)
      ..intensities = List.filled(n, 100.0);

    msg.data.ref.header = StdMsgsHeader(frameId: 'laser').data.ref;

    pub.publish(msg);
    print('published scan: ${msg.ranges.length} ranges, '
        'first=${msg.ranges.first.toStringAsFixed(2)}');
    sleep(const Duration(milliseconds: 250));
  }
}
