// sensor_msgs demo: a simulated ultrasonic range sensor that publishes
// sensor_msgs/msg/Range (generated by rosidl_generator_dart), composing a
// std_msgs/Header from the std_msgs package.
//
// Verify from ROS 2:
//   ros2 topic echo /range sensor_msgs/msg/Range
import 'dart:ffi';
import 'dart:io';
import 'dart:math';
import 'package:rcldart/rcldart.dart' as rcldart;
import 'package:rcldart/src/node.dart';
import 'package:std_msgs/std_msgs.dart';
import 'package:rcldart_example/sensor_msgs_gen/range.dart';

void main() {
  rcldart.RclDart().init();
  final node = rcldart.RclDart().createNode('range_sensor', 'examples');

  final pub = node.createPublisher<SensorMsgsRange>(
    topic_name: '/range',
    messageType: SensorMsgsRange(),
  );
  print('publishing sensor_msgs/msg/Range on /range');

  final rng = Random();
  for (var i = 0; i < 40; i++) {
    final distance = 0.5 + rng.nextDouble() * 3.0; // 0.5 .. 3.5 m

    final msg = SensorMsgsRange()
      ..radiationType = SensorMsgsRange.ULTRASOUND
      ..fieldOfView = 0.26
      ..minRange = 0.02
      ..maxRange = 4.0
      ..range_ = distance
      ..variance = 0.01;

    // Compose a std_msgs/Header (stamp + frame_id) from the std_msgs package.
    final header = StdMsgsHeader(frameId: 'ultrasonic_link');
    msg.data.ref.header = header.data.ref;

    pub.publish(msg);
    print('range = ${distance.toStringAsFixed(2)} m');
    sleep(const Duration(milliseconds: 250));
  }
}
