// End-to-end test: publish a DIFFERENT package's message (example_interfaces,
// not std_msgs) generated by our rosidl_generator_dart, and let `ros2 topic
// echo` confirm ROS 2 receives it.
import 'dart:io';
import 'package:rcldart/rcldart.dart' as rcldart;
import 'package:rcldart/src/node.dart';
import 'package:rcldart_example/example_interfaces_gen/int64.dart';

void main() {
  rcldart.RclDart().init();
  final node = rcldart.RclDart().createNode('ei_pub', 'examples');

  final pub = node.createPublisher<ExampleInterfacesInt64>(
    topic_name: '/ei_test',
    messageType: ExampleInterfacesInt64(),
  );
  print('publisher created for example_interfaces/msg/Int64 on /ei_test');

  for (var i = 0; i < 40; i++) {
    final msg = ExampleInterfacesInt64()..value = 1000 + i;
    pub.publish(msg);
    print('published ${msg.value}');
    sleep(const Duration(milliseconds: 250));
  }
}
